---
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
localAPIEndpoint:
    advertiseAddress: 192.168.1.201
    bindPort: 6443
nodeRegistration:
    name: jugsrv01
    criSocket: "unix:///var/run/crio/crio.sock"
    # remove control-plane taint
    taints: []
