apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  name: my-crossplane-bucket
  namespace: crossplane-system
spec:
  deletionPolicy: Delete
  forProvider:
    acl: private
    locationConstraint: us-east-1
  providerConfigRef:
    name: default
  providerRef:
    name: provider-aws
  writeConnectionSecretToRef:
    name: bucket-secret
    namespace: crossplane-system