apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    # Secret, Filesystem, Environment, InjectedIdentity, None
    source: Secret
    # secretRef, fs, env
    secretRef:
      namespace: crossplane-system
      name: aws-provider-credentials
      key: key