apiVersion: v1
metadata:
  name: ocp4-sno
baseDomain: openshift.lab
compute:
  - name: worker
    replicas: 0
controlPlane:
  name: master
  replicas: 1
networking:
  machineNetwork:
    - cidr: 192.168.1.0/24
  networkType: OVNKubernetes
platform:
  none: {}
# imageContentSources:
#   - source: quay.io/openshift-release-dev/...
bootstrapInPlace:
  installationDisk: /dev/vda
publish: External
pullSecret: '${pull_secret}'
sshKey: '${sshuser_public_key}'